### ISSUE TITLE
Invalid interval bounds and variables needing edits

### ISSUE THREAD

**Issue by patrickgohl** [kundajelab/bpnet-refactor#3]
I tried training a model (on own data) following the tutorial from the README. 
Upon entering the train command I got the following error messages:

Traceback (most recent call last):
  File "/home/pgohl/anaconda3/envs/bpnet/bin/bpnet-train", line 8, in <module>
    sys.exit(main())
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/site-packages/bpnet/cli/bpnettrainer.py", line 132, in main
    args.mnll_loss_background_sample_weight,args.orig_multi_loss)
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/site-packages/bpnet/train/training.py", line 642, in train_and_validate_ksplits
    train_chroms = list(chroms.difference(
AttributeError: 'list' object has no attribute 'difference'

which can be fixed by defining the variable chroms in training.py as a set. Running again after editing the file yields the following error message:

Traceback (most recent call last):
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/site-packages/bpnet/train/training.py", line 352, in train_and_validate
    logging.info("counts loss - {}".format(model_arch_params['counts_loss']))
KeyError: 'counts_loss'

fixed with defining a key value pair for counts_loss in the bpnet_params.json, running again yields:

Traceback (most recent call last):
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/site-packages/bpnet/generators/generators.py", line 643, in _proc_target
    batch = self._generate_batch(batch_df)
  File "/home/pgohl/anaconda3/envs/bpnet/lib/python3.7/site-packages/bpnet/generators/generators.py", line 1086, in _generate_batch
    np.nan_to_num(signal_file.values(chrom, start, end))
RuntimeError: Invalid interval bounds!

No idea how to fix this one.

What am I doing wrong?

**Comment by viramalingam** [comment]
I think it is probably caused by some of the peaks being near the end of the chromosome and when they get resized to the required input size it goes outside the interval. If you could share the peak file it will help to troubleshoot. If that is the case we can modify the code to automatically accommodate that.
